# test:
#   path: /test/{age<\d+>?0}
#   controller: App\Controller\TestController::test
#   methods: [GET, POST]
#   host: localhost
#   schemes: [https, http]
#   # defaults:
#   #   age: 0
#   # requirements:
#   #   age: \d+
